### ISSUE TITLE
Authority lists: ref in epiDoc files

### ISSUE THREAD

**Issue by fra-anthos** [EpiDoc/Tutorials#16]
I'm afraid I still haven't understood fully the function of authority lists and how they are referred to in single xml files. Are authority lists fundamental for indexing, or indexing happens just with mark ups? For example, are namePlaces picked up automatically by being marked? 

I have also noticed that sometimes authority lists are explicitly 'quoted' as xml files (e.g. <persName ref="persons.xml#p0001"/>), whereas in other cases (e.g. <g ref=#interpunct/> or <rs type="occupation" ref="#trousermaker/>) they are not. I suspect this may be because <g/> or <rs type="occupation"/> already point to the respective authority lists (?). In any case, I will have to have separate authority lists for symbols and occapation for the reference to work, is it correct?

Once again, very many thanks for your help, with this and with all my many other questions!

**Comment by gabrielbodard** [comment]
Hi Francesca: yes, that's basically how it works. There are broadly speaking two kinds of indices:

(1) those that use the value of the text in the EpiDoc file as the value of the index, for example index of numbers (by string or value), abbreviations (by the text on the stone or its expansion), words (by the string or lemma) etc. Where you expect these to be unique, or at any rate effectively infinite in possibility, and where you don't need to add any information above what is already in the XML file, you don't need an authority list at all.

(2) those that use a pointer in the EpiDoc file to an item in the authority list with an `@xml:id`, because more information about the indexable item is needed (either for academic or technical reasons). For example (2a) symbols in the XML file are tagged simply as `<g ref="#leaf"/>`, because there is not really a Unicode character you could use to transcribe this character. In an index, you might want to group symbols not only by the name of the glyph you have chosen, but perhaps by type of symbol (various interpuncts, numerical symbols, currency symbols, military abbreviations, say); and you might want to display the name of the symbol in different languages depending on the version of the site being displayed, you might want to display an image or approximation of the leaf (e.g. ❦), or other information. For another example (2b) place-names in the XML are marked with a `<placeName ref="#antioch">` and the place reference as written (often in oblique case, dialect and/or periphrasis), but for the index you would want a standard form of placenames (incorporating both toponyms and ethnics), organisation on geographic rather than alphabetic principles, links to a gazetteer (your own and/or [Pleiades](https://pleiades.stoa.org/)), coordinates, relationships to other places, ecc. ecc. ecc. This information all comes from the authority list—it could not conceivably all be encoding the EpiDoc file for each occurrence of a place reference.
