### ISSUE TITLE
Introduce yourself!

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/Tutorials#6]
Please tell us who you are, what you're working on, and why you wanted to learn EpiDoc…?

**Comment by alessia310** [comment]
Hi everybody. I'm Alessia Lavorante and I'm a PHD student at the University of Naples Federico II. I deal with Herculaneum papyri and my research project aims to carry out the reconstruction, commentary and the edition of a papyrus (PHerc 1413/1416) that preserves an uncertain book of Epicurus' _opus magnum_.
I am also interested in digital papyrology and attended several workshops during these years. The missing piece of my training is EpiDoc and I am very happy and looking forward to learning it with you!

**Comment by mariachiara16** [comment]
Hello! I am Maria Chiara Robustelli and I am from Naples. I graduated in “Filologia, Letterature e Civiltà del Mondo Antico” with a dissertation on an unpublished Herculaneum roll. Until now I have been working on the update of Chartes, an online database of Herculaneum Papyri and I have been attending some digital papyrology courses. I believe this Workshop can be significant in order to complete my training experience in papyri digitalization and represent an important resource able to improve the methods acquired so far.

**Comment by Rossella94** [comment]
Hello everyone!
I'm Rossella Villa, I'm from Naples. I am a PhD student at the University of Cassino. I study Herculaneum papyri and now I'm working on an unpublished roll from the Villa dei Papiri. I'm also keen on Digital Papyrology and I took part to several Digital Papyrology Workshops. I am very glad to attend this  workshop because I think it is a good opportunity to learn how to encode text in TEI XML.

**Comment by adelphae** [comment]
Hi everyone!  My name is Lydia Schriemer and I'm a second year PhD student at the University of Ottawa (cotutelle with St. Andrews).  Broadly speaking my research focuses on the status of women throughout Late Antiquity, but in my dissertation I'm narrowing in on their legal position through the lens of guardianship. I came to EpiDoc via papyri and training in Leiden+ because I'm looking for a manageable way to store, organize, and query the large number of very different source texts (papyri, laws, letters) I'm using for my research.

**Comment by EPiette94** [comment]
Hi everyone!
My name is Elie, PhD candidate coming from Belgium (University of Liege). I have subscribed to this workshop because I am a member of the CGRN (A Collection of Greek Ritual Norms) team who are working on Greek inscriptions regarding sacrificial and purificatory norms (the website is among those proposed on the exercise page). I first took part in it by adding translations and comments in the new inscriptions, and recently I have also begun to encode them. Therefore, I hope to learn some tips to make the coding easier (it is already made as a matter of fact, thanks Gabby for the very helpful cmd+e shortcut) and more generally to better understand how EpiDoc works.
Have a nice day,

Elie

**Comment by eleonoraselvi** [comment]
Hi everyone! I am Eleonora, a PhD student from University of Pisa-University of Siena. My research focuses on Athenian naval inscriptions and their specialized lexicon. EpiDoc training is crucial for my research as I need to digitalize texts, translations and comments. So thanks everybody and have the best learning experience!

**Comment by kruschwitzp** [comment]
Hi all,
My name is Peter Kruschwitz, and I'm based at the University of Vienna. Together with my team, I am working on a five-year project related to the Roman verse inscriptions: http://mappola.eu. Some of my team members have a lot of experience with EpiDoc already, for some of us – including myself – this is a new departure: while I passively gladly use digital resources of others, I normally only use my computer actively as an (extremely powerful) electronic typewriter when I create things. But then "you don't stop learning when you grow old, you grow old when you stop learning"... :-) Very grateful to be here and looking forward to the week.

**Comment by camillacampedelli** [comment]
Hi everyone!
My name is Camilla Campedelli, I'm research fellow at the Berlin- Brandenburg Academy of Sciences and Humanities (Corpus inscriptionum Latinarum) and I teach Latin epigraphy as a "Privatdozent" at the Humboldt University . Since many years I publish inscriptions (including a CIL volume) and now is really time for me to learn how to use Epidoc.

**Comment by ValentinaIannace** [comment]
Hello everyone,
I am Valentina Iannace, I am a PhD student in papyrology at the University of Manchester. For my research project, I work with papyri published and unpublished, of which I provide new editions. As I plan to produce also digital editions of those, or to present new readings of papyri that are already available online, EpiDoc is essential! Thus, many thanks for offering me the possibility to attend this seminar :)

**Comment by DaliaPM** [comment]
Hello everyone!
my name is Dalia Pratali Maffei and I am a PhD student at the University of Cambridge. I am studying the dialect of Hellenistic inscribed epigrams and I find myself using tools such as PHI online everyday. While I am not encoding inscriptions right now, I am planning to make available my editions of Sicilian Hellenistic epigrams and I am looking forward to have a better insight on EpiDoc, which seems more and morre irreplaceable...
Have a nice week everyone!

**Comment by CristinaMestre** [comment]
Hi all!
My name is Cristina Mestre, I am a PhD student in Hellenistic history and Greek epigraphy in western Asia Minor at University College London. I am studying the influence of the Macedonian army in western Asia Minor through the epigraphic evidence, so I use both physical and digital corpora all the time. This has made me realise the importance of digital humanities and how much there is yet to do with them, so I am looking forward to learn about EpiDoc!

**Comment by LauraNast** [comment]
Hi everyone,
I am Laura Nastasi and I am a PhD student at the University of Manchester. I am studying Greek and Latin inscriptions from Roman Corinth. This is my first experience with EpiDoc and I am really happy to have the opportunity to learn how to encode my beloved inscriptions.
Enjoy the workshop :)

**Comment by MhewittOx** [comment]
Hi!
I’m Matthew Hewitt, a 1st year DPhil student at the University of Oxford. My research is focussed on Greek manumission and epigraphic habits. I am eager to learn EpiDoc in order to contribute to other projects for the time being, though I hope also to utilise it for my own research in the future. Looking forward to the week!

**Comment by eddiej2410** [comment]
Hi, I'm Eddie, and I'm a PhD (DPhil) student at Oxford. I work with greek inscriptions (mainly inscribed accounts) but have no experience with EpiDoc. I'm not currently involved in any project, though I hope the workshop will enable me to contribute to one in the near future.

**Comment by DariaRusso** [comment]
Hi everybody, my name is Daria, I am a postdoctoral fellow at the Scuola Superiore Meridionale of the Federico II University in Naples. I am an archaeologist broadly interested in epigraphy. 
Since 2017 I have been a member of the Epigraphic Landscape of Attica project, which has its own database: while filling it with information concerning inscriptions and their findspots, I started wishing to learn something more about the world of epigraphic databases and EpiDoc too .. and so here I am!

**Comment by fra-anthos** [comment]
Hello everyone!

My name is Francesca and I am a Leverhulme ECF at Warwick. My project  involves (ideally) the creation of an inscription database concerning imperial musicians: we have a good number of texts on stone telling us about different performances, honours received by musicians and their travels throughout the Mediterranean. Learning EpiDoc is the first step to the creation of such a database. Perhaps I will have to create some tags about ancient Greek instruments too :)
Please feel free to get in contact if you want to learn more about this or share your own research/project!

**Comment by CarloEmilioBiuzzi** [comment]
Hi everyone, 

my name is Carlo Emilio Biuzzi, I'm a master student at Sapienza University of Rome - Erasmus in Ecole Pratique des Hautes Etudes in Paris. I'm working on Coptic epigraphy and Coptic papyrology; for this reason, I would like to practise myself with EpiDoc in order to bring this competence into this field!

**Comment by abby0412** [comment]
Hi everyone. I'm a PhD candidate at the University of Melbourne in Australia, with an archaeological survey project in (Caucasian) Georgia, but here because of work I am doing/hoping to do to incorporate the Greek and Latin inscriptions of the Regional Epigraphic Catalogues of Asia Minor (British Institute at Ankara) into the Epigraphical Database of Ancient Asia Minor (University of Hamburg). Very much looking forward to learning everything I can this week and to hearing more about everyone's amazing projects.

**Comment by Dany71-Che** [comment]
Hello everybody. I am Daniela Colomo, Research Associate and Curator of the Oxyrhynchus Papyri Collection (Oxford). I work on literary, paraliterary and documentary papyri, and I am particularly interested in ancient rhetoric, ancient education, ancient scholarship and textual criticism, and ancient magic and medicine.

**Comment by liviatagliapietra** [comment]
Hi everyone, 
I am Livia Tagliapietra and I am a postdoctoral Research Associate at the University of Exeter. As part of my current research on language contact in ancient South Italy I am preparing an Epidoc encoded corpus of the inscriptions I am working on. I have attended other courses and workshops in Epidoc, but I am still a beginner and I am trying to receive as much training and support as possible as I work on my corpus. Have a good week everyone!

**Comment by naomicarlessunwin** [comment]
Hello everyone, 

I am Naomi Carless Unwin, a research fellow at the University of Warwick. I work mainly with the epigraphic evidence from Asia Minor; currently, this involves examining inscriptions related to festival culture in the Graeco-Roman East. I use online resources very frequently, and for many years have been planning to undertake EpiDoc training to help understand how I can utilise digital technologies going forward. This is finally the year!

**Comment by Bea90** [comment]
Hi everyone,
I am Beatrice Pestarino. I have just obtained my PhD in Ancient Greek History from UCL. I am working on inscriptions from Cyprus. I am interested in the politico-administrative system of the Cypriot city-kingdoms in the archaic and classical periods.

**Comment by tyassanti** [comment]
Hi everyone,
I am Tyassanti, currently studying old javanese epigraphy at EPHE-PSL. I also take part on Dharma project which mainly speaks about the indian influence in Southeast asia, as well as its script. Principally, what we do in Dharma is not so differend with what this workshop offers, using EpiDoc & other digital humanities' logic. However, as a beginner, I think it's better for me to learn and deepen it here first.

**Comment by CHol-844** [comment]
Hello everyone!

I am Crystal Hollis - a PhD student in archaeology at the University of Exeter and I focus on historic graffiti in churches. Many of my inscriptions are informal and a mixture of Latin and vernacular languages. I am hoping to make some of my graffiti searchable for myself and other researchers. I'm not very good at coding but hoping to learn a lot!

**Comment by nmelvani** [comment]
Hello! I am Nicholas Melvani, research associate at the University of Mainz, Germany. I have published various articles dealing with Byzantine inscriptions and have taught a class in Byzantine epigraphy at the Institute of Historical Research in Athens. I have worked on editing Byzantine inscriptions from Cappadocia in the past and am currently embarking on a new project to publish Byzantine inscriptions on Mount Athos, hopefully with the help of EpiDoc

**Comment by gregoriobarocelli** [comment]
Hello everyone! 
I am Gregorio Barocelli, a Master student at the University of Parma. My main interests are ancient Greek philology, Hellenistic philosophy and early Christian literature. I work on literary and paraliterary papyri. Through Papyri.info I took my first steps into digital humanities applied to ancient studies and I'm very glad to have the opportunity, thanks to this workshop, to strengthen my encoding skills in Epidoc!

**Comment by gpblasdel** [comment]
Hi all! I'm Gavin Blasdel, a PhD candidate in Ancient History at the University of Pennsylvania. My dissertation studies the honorific monuments of Roman Athens and Attica (roughly Sulla to the Herulian sack) from epigraphical, material, and spatial perspectives. I am using Microsoft Access for my database, but am interested in converting to an EpiDoc setup at some point, perhaps later on or after my project is finished. I am also currently working on publishing new Greek and Latin inscriptions from Roman Corinth, so I hope to encode those, too.

**Comment by mzinzi** [comment]
Hello everybody! My name is Mariarosaria Zinzi and I am currently a post-doc researcher at Università degli Studi di Firenze. I am an historical linguist and my main interest is in Greek, Latin and Oscan language.
I am about to take part in a project dealing with some of the languages and cultures of ancient Italy. The aim of the project is to show the forms of linguistic variability in Italy before romanisation. In order to do so, a searchable digital corpus of the inscriptions containing all the relevant contextual information together with their formal representation leveraging the TEI/EpiDoc encoding schema will be created. Therefore, I am attending the workshop in order to learn how to code and have a better insight on EpiDoc!

**Comment by Eleonora93855** [comment]
Hi everybody! I'm Eleonora Angius and I am a graduated student in Classical Philology from Università degli Studi di Roma Tre with a dissertation on the praetorian prefecture's latin epigraphy in Late Antiquity. During the last year I worked on a post-grad project aimed at the production of an epigraphic database in EpiDoc that include the inscriptions of the praetorian prefect of the III-IV Century AD. This work has given me the opportunity to know and appreciate the potential of the TEI/EpiDoc encoding, about which I still have much to learn, and also to experience firsthand the world of the Digital Humanities. So, I am attending the workshop in order to improve and increase my skills in EpiDoc. Have a good week!

**Comment by jimenezji** [comment]
Hi everybody, I'm Nacho Jiménez Chaparro and currently I'm employed as Research support technician in the Reasearch Group named "Archaeology and History of the Roman Empire (AHIR)" of the University of Cantabria (Spain). My duties are focused in geophysic, geomatics an GIS, but also in the development of the website and databases of some proyects of the AHIR Research Group. This research group is involved in a project about epigraphy and mobility in the Roman Empire (www.migra.unican.es). We want to transform the current database of the project in a EpiDoc one. So, i'm interested in get skils in EpiDoc in order tu use it in this project and new ones in the futur. Regards.

**Comment by enabney** [comment]
Hi everyone, I'm Elizabeth Nabney and I've just completed my PhD in papyrology at the University of Michigan, with a focus on family archives and personal letters. I'm interested in learning EpiDoc in order to produce digital editions of some papyri I edited while completing my PhD.

**Comment by dbovet** [comment]
Hi everyone ! I am Dylan Bovet, PhD student at the University of Lausanne, with a thesis project on Latin verse inscriptions. I use markup language to tag metrical features and study the peculiarities of poetic language, so I am already a bit familiar with databases and XML/TEI, but I am also glad to learn from EpiDoc – that I have long been told of – for my current project and further ones involving digital edition.

**Comment by Geles-Alonso** [comment]
Hi everyone! My name is Geles Alonso, I am Lecturer on Ancient History at the UNED (Spain). My research mainly focus on ancient epigraphy and iconography related to physicians and medicine in the Roman world. I am also collaborating in a project that aims to study migration and mobility in the Roman empire through a GIS related to an epigraphical database. Our aim is to transform the current database into an EpiDoc one.
