### ISSUE TITLE
Uncertainty of a lacuna, bilingual text and punctuation

### ISSUE THREAD

**Issue by LauraNast** [EpiDoc/Tutorials#7]
Hi, 
I am trying to encode a fragmentary bilingual text and I have some questions. First, I was wondering whether I should add the language in `<div type="edition" xml:lang="grc">` and then change it when I switch to the other (in the template there is no indication of the language but I've seen it in a video). 
Second, I tried to encode that in ll. 5 and 8 the editor is unsure whether there was a lacuna or not but I cannot see a question mark in EFES. I don't understand what I've done wrong.
Third, is it the indication of the interpunct right? I wasn't sure it was the right way to indicate that. 
![Text](https://user-images.githubusercontent.com/82391866/114738450-44a80400-9d48-11eb-9510-593c34401bdc.png)
![Transcription](https://user-images.githubusercontent.com/82391866/114738470-496cb800-9d48-11eb-918e-143c854680c2.png)
![Efes](https://user-images.githubusercontent.com/82391866/114738494-4eca0280-9d48-11eb-817a-4f546f82a1a7.png)

Thank you!

**Comment by gabrielbodard** [comment]
(1) Re languages, you have two choices:

* if the text is primarily in one language, with a few words or lines in the other, then as you suggest you can mark the `<div type="edition">` as `@xml:lang="la"`, and then in the text use `<foreign xml:lang="grc">` to mark the Greek parts
* if the texts is in two hierarchically equal parts, one in each language, then you can either use two `<div type="textpart" xml:lang="">` to divide them, or if you would prefer not to consider them two separate text parts then I would simply split the `<ab>` element into two parts, and include `@xml:lang` on that (instead of `<div>`).

~~~~
<div type="edition>
  <ab xml:lang="la"><lb/>… <lb/>… <lb/>…</ab>
  <ab xml:lang="grc"><lb/>… <lb/>… <lb/>…</ab>
</div>
~~~~

**Comment by gabrielbodard** [comment]
(2) Your markup for the uncertain lacuna looks correct to me; the Reference Stylesheets must either not be handling that feature, or expecting slightly different combination of attributes.

For now don't worry about it, but if you very much want to see this fixed in the future, I would suggest writing to the Markup list and someone (possibly me!) will look at the XSLT and see if we can figure out what's wrong.

**Comment by gabrielbodard** [comment]
(3) `<g type="interpunct"/>` is an old-fashioned way of encoding this in EpiDoc. The correct way is now to use `<g ref="#interpunct"/>` and have an element with `@xml:id="interpunct"` in the symbols authority list that defines how you want that to be displayed (as words or as a Unicode character, for example). The stylesheets will still render the former correctly, as a legacy feature, but that won't last forever.

**Comment by LauraNast** [comment]
Ok, great! Thank you very much!
