### ISSUE TITLE
Project criteria and details in xml file

### ISSUE THREAD

**Issue by fra-anthos** [EpiDoc/Tutorials#8]
This question originates from my partial knowledge of epigraphy, so apologies if it sounds awkward. I am working with a series of inscriptions collected in other editions, and I have been able to find info about current location, repository and catalogue numbers only for some of my texts. It seems that these details have been omitted by previous editors because they were more interested in the literary aspect of the texts. Is it possible to leave out such data if unknown? Have you found yourselves in a similar situation before?

Many thanks in advance!

**Comment by IreneVagionakis** [comment]
Yes, it happens very often! You can simply omit the pieces of information that are not provided, or otherwise you can write something like 'data N/A', 'unknown' or a similar phrasing.

**Comment by CHol-844** [comment]
My question relates to this - I work primarily with graffiti so there is no repository, most of the time the inscription is damaged or overlaid with other graffiti, and the only records are usually grey literature that are not available to scholars. What is the best way to encode these sort of things when there is so little information about the object save for where it is located? Do we just leave these sections blank or is there a convention used to fill in the blanks to demonstrate the information exists but is not accessible? 

Thanks!

**Comment by IreneVagionakis** [comment]
The sections can be simply left blank, yes (except for the `<repository>`, that needs always to be included and to have some content), but, if you want to make clear that you have not been able to find such information, you can write something like 'information not available/accessible'. I am not aware of any conventional/shared definition for such cases, but I think that 'N/A' is one of the most common ways to say it.

**Comment by gabrielbodard** [comment]
The one thing you can (I think) do in the `<msIdentifier>` section, for a text that has no repository (as many inscriptions, and especially as you say, graffiti), is instead of giving it a repository and idno, instead use `<msName>`, which is just a place to say "What people normally call this text"—which, if there is no _convention_ for this text yet, is just your label for it. (It might, however, be useful to check if any institution has in fact catalogued and taken "ownership" of this graffito, as for example the graffiti in Pompeii almost certainly are. Maybe graffiti in a modern church not so much. :) )

**Comment by hcayless** [comment]
Unless I’m mistaken, you’re not required to provide a repository. You can supply a location instead. Any element in https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-model.placeNamePart.html.

**Comment by Bea90** [comment]
Just out of curiosity. Are there XML guidelines for inscriptions which are not written in Greek and Latin but in Phoenician? I have some bilingual inscriptions in Greek and Phoenician, I was wondering if I could use the same couple of programmes Oxygen/EFES to display them once I encoded them. 
Thank youuu!!

**Comment by IreneVagionakis** [comment]
The EpiDoc Guidelines are valid for all the epigraphic (& papyrological) traditions (at least ideally!), even if the majority of the current examples are in Latin and Greek. So, you can use EpiDoc with Oxygen and EFES also for Phoenician inscriptions, after installing an appropriate font and adjusting the layout to handle the right-to-left writing direction.

**Comment by gabrielbodard** [comment]
I would turn the question back on @Bea90 : are there any features of Phoenician inscriptions that you think are not handled by the current EpiDoc Guidelines or Stylesheets? We would be very interested in look at them and see if they could be enhanced accordingly.

**Comment by Bea90** [comment]
Yes! Thank you for the question. We do not transcribe anymore from right to left in Hebrew scripts but from left to right in Latin scripts. The problem is when there is something 'unclear'. We cannot use the dot under the letters because some letters are already transcribed with a phonetic dot under them for example  Ḥ or Ṭ or ṣ́, shade. So in this case if you look at the editions in the books, some editors use a little circle above the letter. I attach a picture, see M and K in line7. I did not find this in the guidelines, maybe I just lost it. I also know they are creating an online corpus with all the Phoenician inscriptions we know  [http://cip.cchs.csic.es/home](url) so perhaps they have a convention or they own guidelines. But as far as I understood there is anything published yet.
![WhatsApp Image 2021-04-16 at 12 50 48](https://user-images.githubusercontent.com/81052414/115020481-8e146280-9eb2-11eb-9964-c6fe5a2c376d.jpeg)
Thank you very much
Beatrice

**Comment by Bea90** [comment]
anyways, yes it would be great to have the 'unclear' tag for Phoenician too thank you :)

**Comment by IreneVagionakis** [comment]
Semantically, `<unclear>` remains the right element to be used for this. What is needed, so, is an appropriate rendering of the `<unclear>` when the `@xml:lang` is Phoenician, and possibly to include in the Guidelines some examples taken from Phoenician texts: you can ask for both by adding a Feature request ticket [here](https://sourceforge.net/p/epidoc/feature-requests/).

**Comment by gabrielbodard** [comment]
There are already Leiden-styles defined in EpiDoc that use different rendering for `<unclear>`, and it would be trivial to add a transcription style (e.g. for Phoenician, or more specifically for one community or project) that uses the Unicode character of combining circle above rather than underdot to display this feature. If we had time to talk about customising of XSLT in this workshop, I would show you how to do it. :)

**Comment by Bea90** [comment]
yes, this would be great! thank you
________________________________

**Comment by simonastoyanova** [comment]
Hi all,
I recently added a rule to the Schematron for the Crossreads project, where if the `@xml:lang` of `<div type="edition">` is xpu-Latn, the underdot is allowed and another character is flagged when an `<unclear>` is needed. I've tested it with a couple of transliterated texts but we haven't actually gotten to our Phoenician texts, so further testing might be necessary. 
See here, lines 31-44: https://github.com/ISicily/ISicily/blob/master/schematron/ircyr-checking.sch . That's just for checking our encoding as we work, though, we haven't yet tackled the display side of it. Hope that helps!
